# Generated by Django 6.0.1 on 2026-04-28 10:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Link thân thiện')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả danh mục')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Ảnh đại diện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Người nhận')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(verbose_name='Địa chỉ chi tiết')),
                ('delivery_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí giao hàng')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPING', 'Đang giao hàng'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='SoilRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ph_level', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên chi nhánh')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Vị trí tọa độ')),
                ('delivery_radius', models.IntegerField(default=5000, help_text='Đơn vị: mét', verbose_name='Bán kính giao hàng')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branch_images/', verbose_name='Ảnh cửa hàng')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='Giờ mở cửa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chi nhánh cửa hàng',
                'verbose_name_plural': 'Các chi nhánh cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên cây')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Giá bán')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Vườn ươm')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Hình ảnh')),
                ('is_available', models.BooleanField(default=True)),
                ('min_temp', models.FloatField(default=20.0, verbose_name='Nhiệt độ Min (°C)')),
                ('max_temp', models.FloatField(default=35.0, verbose_name='Nhiệt độ Max (°C)')),
                ('min_ph', models.FloatField(default=5.5, verbose_name='pH Min')),
                ('max_ph', models.FloatField(default=7.5, verbose_name='pH Max')),
                ('max_clay', models.FloatField(default=60.0, verbose_name='Tỷ lệ Sét tối đa (%)')),
                ('min_humidity', models.FloatField(default=40.0, verbose_name='Độ ẩm Min (%)')),
                ('max_humidity', models.FloatField(default=100.0, verbose_name='Độ ẩm Max (%)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='OSS.category')),
            ],
            options={
                'verbose_name': 'Cây cảnh',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá lúc mua')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='OSS.order')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OSS.plant', verbose_name='Cây cảnh')),
            ],
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/gallery/', verbose_name='Hình ảnh chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='OSS.plant')),
            ],
            options={
                'verbose_name': 'Ảnh chi tiết cây',
                'verbose_name_plural': 'Thư viện ảnh',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Quản trị'), ('customer', 'Người dùng')], default='customer', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ giao hàng')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.CreateModel(
            name='EmailChangeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='OSS.storebranch', verbose_name='Chi nhánh')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storestock', to='OSS.plant')),
            ],
            options={
                'verbose_name': 'Kho hàng chi nhánh',
                'verbose_name_plural': 'Quản lý kho hàng',
                'unique_together': {('branch', 'plant')},
            },
        ),
    ]
