# Generated by Django 6.0.1 on 2026-05-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OSS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailChangeOTP',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
        migrations.DeleteModel(
            name='RegistrationOTP',
        ),
    ]
